### ISSUE TITLE
[2.1-27] Name changes on server

### ISSUE THREAD

**Issue by kepaik** [SanaMobile/vaccine_registry#12]
We entered a record with the username ANM007 and entered the name as “Robin Hood” (bac43582-fb12-43e0-83b8-28337f70219d), however it is being displayed correctly on the server as “Anna Schrimpf”. Looking up, it still displays as Robin Hood.

**Comment by ewinkler** [comment]
This may be a side effect that caused by a combination of the edit not pushing on the server and the older version defaulting to selecting the first when more than one patient was returned on the id query. The id query now returns a list which may eliminate some of the problem. The server edit is posted as another issue.
