### ISSUE TITLE
[2.1-28] No VACCID popup for new barcodes falsely scanned as returning

### ISSUE THREAD

**Issue by AnnaSchrimpf** [SanaMobile/vaccine_registry#43]
I'd like to understand this better - what will this do to the data in the backend?

Also, if I follow the instructions and re-scan, I'm still returning to the same screen rather than moved forward.

**Comment by kepaik** [comment]
Possibly related to scan flow issue.
What we were trying to clarify previously, is the distinct state between 1) Returning children that forgot their AADHAR, and 2) New children without any id.

The exception states are where:
1) Returning children have a VACCID that is not found in the DB. This used to result in the system automatically assuming it is a new child. This did not appropriately catch the cases where there were possibly mistyped on manual entry. Instead of proceeding as a new child, we wanted to give them an opportunity to rescan or explicitly identify as a new child.

2) With new children, the scanned VACCID would be checked for duplication to be sure it does not conflict with any other records. In that case, we would recommend they throw out that barcode and attach another one.
