### ISSUE TITLE
[2.1-28.2] Different records display on tpk-vacc and amazonaws servers

### ISSUE THREAD

**Issue by AnnaSchrimpf** [SanaMobile/vaccine_registry#46]
![screen shot 2016-10-04 at 8 04 59 pm](https://cloud.githubusercontent.com/assets/5496869/19096949/d2031fde-8a6e-11e6-821e-f4e391493058.png)
I'm seeing different encounters here:
https://ec2-52-66-129-146.ap-south-1.compute.amazonaws.com/mds/admin/core/encounter/
Vs. https://tpk-vacc.org/mds/admin/core/encounter/

**Comment by kepaik** [comment]
https://tpk-vacc.org/mds/admin/core/encounter/ should be the sole data repo moving forward.

**Comment by francineloza** [comment]
Thanks! None of the records that we added yesterday are showing up. Also, I tried to add a few records now and they dont show up either. On the tablet- last sync date is today, screenshot attached. 
![screenshot_2016-10-05-16-26-48](https://cloud.githubusercontent.com/assets/5846697/19130661/1b52ad34-8b1a-11e6-8a45-8f2bf23e5147.png)

**Comment by AnnaSchrimpf** [comment]
We still don't see any of the records we entered on the server.

**Comment by ewinkler** [comment]
The data is going to the tpk-vacc.org host but I am seeing some errors that the patient does not exist. I think this is a side effect of:

1. The server updates were not in place when the initial patient records were created.
2. The client resend only triggering when the connectivity changes. See issue #53.

Issue #53 will be fixed in the next release.  In the interim, activating and deactivating airplane mode on the device will trigger the resend. Obviously, that is not an acceptable solution when deployed but should get any data currently on the tablet to the server until #53 is resolved in the next release.

Going forward, the tpk-vacc.org server will be solely for data coming from the field. We will be shifting to a different testing server and the url will be provided. Clients provided for testing and production release will be configured to upload to the correct server.

**Comment by AnnaSchrimpf** [comment]
When will you be ready to share the next release?

**Comment by ewinkler** [comment]
Our target is to have the client update available by Saturday.

**Comment by kepaik** [comment]
Backend data seems to be syching properly.
